"""
E2E tests for the CLI-only flow (no config files).

Runs the factory container with source repo, ref, and workspace path provided
entirely via CLI arguments.  No source.json or plugins-list.yaml is mounted;
the factory auto-discovers plugins and computes build arguments.  Validates
that the generated plugins-list.yaml matches expected output and that the
single plugin is built successfully.
"""

from pathlib import Path

import pytest
import yaml

from .conftest import (
    FIXTURES_DIR,
    ContainerResult,
    PluginBuildTests,
    parse_plugins_from_config,
)

CLI_ONLY_FIXTURE_DIR = FIXTURES_DIR / "cli-only"


@pytest.fixture(scope="class")
def cli_config_dir(tmp_path_factory: pytest.TempPathFactory) -> Path:
    """Create an empty temp directory for the container to write config into."""
    return tmp_path_factory.mktemp("cli-only-config")


@pytest.fixture(scope="class")
def container_result(run_factory_container, cli_config_dir) -> ContainerResult:
    """Run the factory container with all source config via CLI arguments."""
    return run_factory_container(
        cli_config_dir,
        extra_args=[
            "--source-repo", "https://github.com/backstage/community-plugins",
            "--source-ref", "ebc1e1a7a73915bdf7c1aac6350ebc00219afeb0",
            "--workspace-path", "workspaces/scaffolder-relation-processor",
        ],
    )


@pytest.fixture(scope="class")
def expected_plugins(cli_config_dir) -> list[str]:
    """Plugin paths from the generated plugins-list.yaml (available after container run)."""
    return parse_plugins_from_config(cli_config_dir)


@pytest.mark.e2e
class TestCliOnly(PluginBuildTests):
    """Validate the CLI-only flow with no config files on disk."""

    def test_plugins_list_was_generated(self, cli_config_dir) -> None:
        generated = cli_config_dir / "plugins-list.yaml"
        assert generated.exists(), (
            "plugins-list.yaml was not generated by the factory"
        )

    def test_generated_build_args_match_expected(self, cli_config_dir) -> None:
        generated = yaml.safe_load(
            (cli_config_dir / "plugins-list.yaml").read_text()
        )
        expected = yaml.safe_load(
            (CLI_ONLY_FIXTURE_DIR / "expected-plugins-list.yaml").read_text()
        )
        assert generated == expected, (
            "Generated plugins-list.yaml does not match expected.\n"
            f"Generated: {generated}\n"
            f"Expected:  {expected}"
        )
