"""
E2E tests for the CLI-only flow (no config files).

Runs the factory container with source repo, ref, and workspace path provided
entirely via CLI arguments.  No source.json or plugins-list.yaml is mounted;
the factory auto-discovers plugins and computes build arguments.  Validates
that the generated plugins-list.yaml matches expected output and that the
single plugin is built successfully.
"""

from pathlib import Path

import pytest
import yaml

from .conftest import (
    FIXTURES_DIR,
    ContainerResult,
    assert_no_errors_in_logs,
    find_outputs_for_plugin,
    get_output_integrity_files,
    get_output_tgz_files,
    parse_plugins_from_config,
)

CLI_ONLY_FIXTURE_DIR = FIXTURES_DIR / "cli-only"


@pytest.fixture(scope="class")
def cli_config_dir(tmp_path_factory: pytest.TempPathFactory) -> Path:
    """Create an empty temp directory for the container to write config into."""
    return tmp_path_factory.mktemp("cli-only-config")


@pytest.fixture(scope="class")
def cli_result(run_factory_container, cli_config_dir) -> ContainerResult:
    """Run the factory container with all source config via CLI arguments."""
    return run_factory_container(
        cli_config_dir,
        extra_args=[
            "--source-repo", "https://github.com/backstage/community-plugins",
            "--source-ref", "ebc1e1a7a73915bdf7c1aac6350ebc00219afeb0",
            "--workspace-path", "workspaces/scaffolder-relation-processor",
        ],
    )


@pytest.fixture(scope="class")
def expected_plugins(cli_config_dir) -> list[str]:
    """Plugin paths from the generated plugins-list.yaml (available after container run)."""
    return parse_plugins_from_config(cli_config_dir)


@pytest.mark.e2e
class TestCliOnly:
    """Validate the CLI-only flow with no config files on disk."""

    def test_container_exits_successfully(self, cli_result: ContainerResult) -> None:
        assert cli_result.returncode == 0, (
            f"Container exited with code {cli_result.returncode}\n"
            f"Full log: {cli_result.log_file}\n"
            f"output:\n{cli_result.output[-3000:]}"
        )

    def test_no_errors_in_logs(self, cli_result: ContainerResult) -> None:
        assert_no_errors_in_logs(cli_result)

    def test_plugins_list_was_generated(self, cli_config_dir) -> None:
        generated = cli_config_dir / "plugins-list.yaml"
        assert generated.exists(), (
            "plugins-list.yaml was not generated by the factory"
        )

    def test_generated_build_args_match_expected(self, cli_config_dir) -> None:
        generated = yaml.safe_load(
            (cli_config_dir / "plugins-list.yaml").read_text()
        )
        expected = yaml.safe_load(
            (CLI_ONLY_FIXTURE_DIR / "expected-plugins-list.yaml").read_text()
        )
        assert generated == expected, (
            "Generated plugins-list.yaml does not match expected.\n"
            f"Generated: {generated}\n"
            f"Expected:  {expected}"
        )

    def test_all_plugins_produce_tgz(
        self,
        cli_result: ContainerResult,
        expected_plugins: list[str],
    ) -> None:
        tgz_files = get_output_tgz_files(cli_result.output_dir)

        for plugin_path in expected_plugins:
            matches = find_outputs_for_plugin(plugin_path, tgz_files)
            assert matches, (
                f"No .tgz output found for plugin '{plugin_path}'\n"
                f"Available tgz files: {[f.name for f in tgz_files]}"
            )

    def test_all_plugins_produce_integrity(
        self,
        cli_result: ContainerResult,
        expected_plugins: list[str],
    ) -> None:
        integrity_files = get_output_integrity_files(cli_result.output_dir)

        for plugin_path in expected_plugins:
            matches = find_outputs_for_plugin(plugin_path, integrity_files)
            assert matches, (
                f"No .tgz.integrity output found for plugin '{plugin_path}'\n"
                f"Available integrity files: {[f.name for f in integrity_files]}"
            )

    def test_output_tarballs_are_nonzero(
        self, cli_result: ContainerResult
    ) -> None:
        tgz_files = get_output_tgz_files(cli_result.output_dir)
        assert tgz_files, "No .tgz files found in output directory"

        for tgz in tgz_files:
            assert tgz.stat().st_size > 0, f"Tarball is empty: {tgz.name}"

    def test_output_count_matches_plugins(
        self,
        cli_result: ContainerResult,
        expected_plugins: list[str],
    ) -> None:
        tgz_files = get_output_tgz_files(cli_result.output_dir)
        assert len(tgz_files) >= len(expected_plugins), (
            f"Expected at least {len(expected_plugins)} tgz outputs "
            f"(one per plugin), got {len(tgz_files)}.\n"
            f"Plugins: {expected_plugins}\n"
            f"Outputs: {[f.name for f in tgz_files]}"
        )
